#!/usr/bin/env bash
# NOSE - run every standing gate and say plainly whether all are green.
#
#   bash scripts/gates.sh          ends with ALL GATES GREEN, or exits 1
#
# Each gate passes only on its exact expected line - a crash, a missing
# dependency or a changed count fails it. The expected counts are the ones in
# PARSER-HANDOFF.md section 2; when a session legitimately changes the corpus,
# update them here in the same commit, so this fails loudly rather than
# drifting quietly.
#
# Needs the Codespace setup: npm install done, test/fixtures/extracted
# generated by test/extract-dump.js, network for build.sh's QR download.
# bash build.sh writes netlify/functions/lib/build-info.json, which is
# gitignored: a Codespace build records deployContext "dev", and none of the
# gates below can store anything in the archive.
set -uo pipefail
cd "$(dirname "$0")/.."

failed=0

# gate <label> <expected, as shown> <ERE matched against whole lines> <command...>
gate() {
  local label=$1 shown=$2 pattern=$3
  shift 3
  local out line
  out=$("$@" 2>&1)
  line=$(grep -E -m1 -- "$pattern" <<<"$out")
  if [ -n "$line" ]; then
    printf 'ok    %-15s %s\n' "$label" "$line"
  else
    printf 'FAIL  %-15s expected: %s\n' "$label" "$shown"
    grep -v '^[[:space:]]*$' <<<"$out" | tail -4 | sed 's/^/                  | /'
    failed=$((failed + 1))
  fi
}

anchors() {
  node -e '
    const fs = require("fs");
    const { parseCoa } = require("./netlify/functions/lib/parse-coa.js");
    const total = id => parseCoa(fs.readFileSync(`test/fixtures/extracted/${id}.txt`, "utf8")).totalTerpenes;
    console.log(`KAY-CAR-001 ${total("KAY-CAR-001")} KAY-PRR-001 ${total("KAY-PRR-001")}`);
  '
}

gate 'coa gate'       '56 accepted / 3 rejected' '^56 accepted / 3 rejected$' \
  node test/coa-gate-test.js test/fixtures/extracted netlify/functions/lib/parse-coa.js
gate 'parity'         '56 match / 0 differ'      '^56 match / 0 differ( |$)' \
  node test/extraction-parity.js test/fixtures/pdf
gate 'fixture lint'   'corpus clean'             '^corpus clean$' \
  node test/fixture-lint.js
gate 'resolver'       'resolver clean'           '^resolver clean$' \
  node test/resolver-test.js
gate 'kaycha anchors' 'KAY-CAR-001 4.124 KAY-PRR-001 0.944' '^KAY-CAR-001 4\.124 KAY-PRR-001 0\.944$' \
  anchors
gate 'store'          'store clean'              '^store clean$' \
  node test/store-test.js
gate 'probe logic'    'probe-test clean'         '^probe-test clean$' \
  node test/probe-test.js
gate 'archive wiring' 'archive-wiring clean'     '^archive-wiring clean$' \
  node test/archive-wiring-test.js
gate 'archive scripts' 'archive-scripts clean'   '^archive-scripts clean$' \
  node test/archive-scripts-test.js
gate 'build'          'OK — ready to deploy'     '^OK — ready to deploy$' \
  bash build.sh

echo
if [ "$failed" -eq 0 ]; then
  echo 'ALL GATES GREEN'
else
  echo "GATES FAILED: $failed - do not commit"
  exit 1
fi
